# Generated by Django 4.2.5 on 2023-09-19 13:05

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Medicine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField()),
                ("cost_price", models.FloatField()),
                ("selling_price", models.FloatField()),
                ("quantity", models.IntegerField()),
                (
                    "medicine_type",
                    models.CharField(
                        choices=[
                            ("Tablet", "Tablet"),
                            ("Syrup", "Syrup"),
                            ("Injection", "Injection"),
                            ("Ointment", "Ointment"),
                            ("Capsule", "Capsule"),
                            ("Drops", "Drops"),
                        ],
                        max_length=100,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Medicines",
            },
        ),
    ]
